# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 905d238e75e890889fd4bde969e722cce4f309f92e70a7fe78adb73f655c64833c4c8cc438f07f4c13ffc3a3adf44a71752c5f2bf30366bb2d6ed772ae1d79db

test:
  secret_key_base: bb80a191491167fc0cbbfb50d77f32c07e4a7b25da6cb403aaa18f369fb35d64b52518fdeaa0a612a5577c398ce157cfb50dd53737e3d26ba869879278f2733d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
